### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tarbax** [hasscontrol/hasscontrol#26] opened 2021-07-10 10:42 UTC
I read an tried both ways with and without long lived access token and I always get the iq logo with an ! On it. Tried on my father's phone and watch to also without success.
![1625913604428576926245204921797](https://user-images.githubusercontent.com/34491557/125160211-07eb7d80-e17c-11eb-80ce-9294dcf54421.jpg)
Garmin venu and a vivoactive 4
Connect iq was always opened in the phone. The older hassiq does work without issues but it's to outdated and not optimized for a smartwatch.

**Comment by karlenek** [comment] 2021-07-10 19:25
The IQ logo comes when the app crashes due to an unhandled error. What phone are you using? Android or iOS, and what version?

In what state do the app crash? When you have entered your password and pressed login?
Do you have characters other than number and English letters in your entities/groups or home assistant url?

Would you mind debugging the app to give some more information? See link below, basic debugging.

https://developer.garmin.com/connect-iq/core-topics/debugging/

**Comment by tarbax** [comment] 2021-07-11 12:09
> The IQ logo comes when the app crashes due to an unhandled error. What phone are you using? Android or iOS, and what version?
> 
> In what state do the app crash? When you have entered your password and pressed login?
> Do you have characters other than number and English letters in your entities/groups or home assistant url?
> 
> Would you mind debugging the app to give some more information? See link below, basic debugging.
> 
> https://developer.garmin.com/connect-iq/core-topics/debugging/

i am using samsung s20+
and the other smartwatch is linked to a samsung note 8
on both phone the iq app is running and responding

ill try to get a log with the debugging tool. cant find the download for osx tho..

**Comment by tarbax** [comment] 2021-07-11 12:27
i installed eclipse and the sdk but i have no clue how to debug it now

**Comment by karlenek** [comment] 2021-07-11 13:04
I think as a first step it’s enough to just retrieve the device logs. If you follow the steps for “ Basic Debugging”, it’s described how to enable logging in the end of that section.

Basically you just create a file with the same name as the app in `/GARMIN/APPS/LOGS/APPNAME.TXT` on the device. You can find the name of the app in `/GARMIN/APPS`. The you run the app and try to login, when it has crashed you just download the .TXT file and hopefully there is some logs in there!

If you are using OSX, you can use the program `Android File Transfer` to create the .txt file and transfer it to the computer after the app has crashed.

**Comment by tarbax** [comment] 2021-07-12 19:01
![image](https://user-images.githubusercontent.com/34491557/125341764-4a67b280-e354-11eb-842f-f7882b543b2d.png)
wont give me a log

**Comment by karlenek** [comment] 2021-07-13 05:35
@tarbax, you need to name it according to what the app has been named on your watch. I think the app should be named something like H123456.PRG or something similar. The app is named during installation, therefore I can’t give you the name.

**Comment by tarbax** [comment] 2021-07-14 13:45
@karlenek 
my log:

Initializing with long-lived access token
Loaded entities: []
Initializing with long-lived access token
Loaded entities: []
Initializing with long-lived access token
Loaded entities: []

**Comment by karlenek** [comment] 2021-07-20 20:08
@tarbax,
Have you specified any scenes or entities in the ConnectIQ settings?
If you have, could you post exactly what you have in that input field?

Can you see a loading text before the app crashes?

**Comment by ianwestcott** [comment] 2021-07-21 14:46
I had a similar issue setting up the widget as a new user, on a vivoactive 4S paired with an iOS device, with a long-lived token configured in the app settings. Initially I only had a group configured. The widget would say "no entities" with a frowny face, and then show the IQ error screen above. I then created some scenes and added those to the widget's configuration, and now the app loads correctly. Is it possible that the issue is related to configuring only groups but no scenes?

**Comment by tarbax** [comment] 2021-07-21 17:11
I have no scènes on home assistant so can't even add any of it. @ianwestcott will be probably be right

**Comment by karlenek** [comment] 2021-07-21 19:22
@tarbax, I think this happens when you press the select button to "toggle" an entity when there are no entities loaded. Is this when it crash occurs?

You need to open the menu first and go into settings and "Refresh entities". https://github.com/hasscontrol/hasscontrol#group-sync

I have also published a new version that will capture the error and show an message advising to refresh entities, instead of crashing the app. It should be available to download from Garmin in a few hours, sometimes it goes faster. 

Please let me know how it goes, so we can close the issue :)

/Karl

**Comment by tarbax** [comment] 2021-08-01 17:38
It works now without long lived access token.
Seems that I needed to keep my watch awake when logging in for it to work.
When I enter a long lived access token I get a message that authentication has failed

**Closed** 2021-08-11 22:05 UTC
Labels: bug
